import { ResolvedModNode, BuildContext, ExportManifest } from '../types/mod';

export class ExporterService {
  /**
   * Flattens node tree into unique list of resolved mods with valid files
   */
  static getUniqueModFiles(nodes: ResolvedModNode[]): ResolvedModNode[] {
    const map = new Map<string, ResolvedModNode>();
    
    function traverse(node: ResolvedModNode) {
      if (node.file && !map.has(node.key)) {
        map.set(node.key, node);
      }
      for (const child of node.dependencies) {
        traverse(child);
      }
    }

    nodes.forEach(traverse);
    return Array.from(map.values());
  }

  /**
   * Export format 1: Simple mods.txt
   */
  static exportModsTxt(nodes: ResolvedModNode[]): string {
    const items = this.getUniqueModFiles(nodes);
    let output = `# Minecraft Modpack List\n# Generated by Mod Seeker App\n\n`;

    items.forEach(item => {
      output += `${item.name} (${item.platform}) -> ${item.file?.fileName || 'NO FILE'}\n`;
      if (item.file?.downloadUrl) {
        output += `${item.file.downloadUrl}\n`;
      }
      output += `\n`;
    });

    return output;
  }

  /**
   * Export format 2: Packwiz format (.pw.toml)
   */
  static exportPackwiz(nodes: ResolvedModNode[], context: BuildContext): string {
    const items = this.getUniqueModFiles(nodes);
    let output = `[pack]\nname = "Custom Modpack"\nauthor = "Mod Seeker User"\nversion = "1.0.0"\n\n[versions]\nminecraft = "${context.gameVersion}"\n${context.modLoader} = "latest"\n\n[files]\n`;

    items.forEach(item => {
      if (item.file) {
        output += `[[files]]\nfilename = "${item.file.fileName}"\nside = "both"\n`;
        output += `[files.download]\nurl = "${item.file.downloadUrl}"\nmode = "url"\n\n`;
      }
    });

    return output;
  }

  /**
   * Export format 3: Launcher JSON Manifest
   */
  static exportJsonManifest(nodes: ResolvedModNode[], context: BuildContext): string {
    const items = this.getUniqueModFiles(nodes);
    
    const manifest: ExportManifest = {
      gameVersion: context.gameVersion,
      modLoader: context.modLoader,
      createdTime: new Date().toISOString(),
      mods: items.map(item => ({
        name: item.name,
        slug: item.slug,
        fileName: item.file?.fileName || '',
        downloadUrl: item.file?.downloadUrl || '',
        platform: item.platform,
        isDependency: item.isDependency
      }))
    };

    return JSON.stringify(manifest, null, 2);
  }

  /**
   * Triggers a browser download for text content
   */
  static downloadTextFile(filename: string, content: string, mimeType = 'text/plain') {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}
